<a href="https://colab.research.google.com/github/Vicky-Mends/ML/blob/main/Preparing_data_for_a_machine_learning_task_negotiating_salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/Vicky-Mends/ML/main/data%20(3).csv"
)

In [5]:
df

,job_id,job_text,year,metro,remote,degree_required,company_type,years_experience,salary_usd
0,XKJPJ3,staff product manager (B2B),2020,Austin TX,0,bachelors,startup,10,218205
1,3GFIFX,senior cloud infrastructure engineer (cloud),2024,Boston,0,bachelors,corp,6,208804
2,OTXU8G,cloud infrastructure engineer (cloud),2024,San Francisco,0,masters,big_tech,3,283959
3,P86VBI,frontend engineer (new grad) (distributed syst...,2016,Austin TX,1,bachelors,corp,1,133057
4,XDI07I,senior full stack engineer (platform),2021,Seattle,1,bachelors,corp,9,270402
...,...,...,...,...,...,...,...,...,...
1595,WVPHUR,BI analyst (entry level) (experimentation),2021,San Francisco,0,bachelors,corp,0,129758
1596,WZSZMI,mobile app developer (entry level) (payments),2025,Seattle,0,bachelors,corp,0,168929
1597,V1Y0J1,principal office administrator (operations),2021,St. Louis,0,bachelors,small_business,13,76086
1598,S85ODA,product manager (growth),2024,Seattle,0,bachelors,small_business,5,205385
1599,WDS75K,mobile app developer intern,2022,Austin TX,0,masters,big_tech,0,229205

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            1600 non-null   object
 1   job_text          1600 non-null   object
 2   year              1600 non-null   int64
 3   metro             1600 non-null   object
 4   remote            1600 non-null   int64
 5   degree_required   1600 non-null   object
 6   company_type      1600 non-null   object
 7   years_experience  1600 non-null   int64
 8   salary_usd        1600 non-null   int64
dtypes: int64(4), object(5)
memory usage: 112.6+ KB

In [ ]:
df.describe()

              year       remote  years_experience     salary_usd
count  1600.000000  1600.000000       1600.000000    1600.000000
mean   2021.548750     0.098750          4.375625  176514.763750
std       2.180733     0.298419          3.699234   75573.819681
min    2016.000000     0.000000          0.000000   27841.000000
25%    2020.000000     0.000000          1.000000  122738.000000
50%    2022.000000     0.000000          4.000000  167784.000000
75%    2023.000000     0.000000          6.000000  218784.000000
max    2025.000000     1.000000         15.000000  420000.000000

In [ ]:
df.head(3)

,job_id,job_text,year,metro,remote,degree_required,company_type,years_experience,salary_usd
0,XKJPJ3,staff product manager (B2B),2020,Austin TX,0,bachelors,startup,10,218205
1,3GFIFX,senior cloud infrastructure engineer (cloud),2024,Boston,0,bachelors,corp,6,208804
2,OTXU8G,cloud infrastructure engineer (cloud),2024,San Francisco,0,masters,big_tech,3,283959

In [ ]:
df.sample(7)

,job_id,job_text,year,metro,remote,degree_required,company_type,years_experience,salary_usd
1577,EB8JWU,operations analyst,2022,Boston,0,none,small_business,3,108836
62,60AOBR,junior business analyst,2019,San Francisco,0,bachelors,big_tech,1,208277
1541,HTCMIJ,frontend engineer (payments),2019,Dallas,0,bachelors,corp,3,110511
897,JRW9VK,lead data analyst (dashboarding),2021,Seattle,0,bachelors,corp,11,156401
1145,1JQYRA,junior applied scientist (computer vision),2025,Bloomington IN,0,masters,small_business,2,128634
1417,KY3BE7,program manager (entry level),2021,Philadelphia,0,bachelors,corp,1,140904
1343,XRFIMO,lead data analyst (SQL),2023,Austin TX,1,bachelors,small_business,9,166932

In [ ]:
df.duplicated().sum() #no duplicates

np.int64(0)

In [ ]:
X = df[["job_text","year","metro","remote","degree_required","company_type","years_experience"]]
y = df["salary_usd"]

In [ ]:
X.shape

(1600, 7)

In [ ]:
y.shape

(1600,)

In [ ]:
X

,job_text,year,metro,remote,degree_required,company_type,years_experience
0,staff product manager (B2B),2020,Austin TX,0,bachelors,startup,10
1,senior cloud infrastructure engineer (cloud),2024,Boston,0,bachelors,corp,6
2,cloud infrastructure engineer (cloud),2024,San Francisco,0,masters,big_tech,3
3,frontend engineer (new grad) (distributed syst...,2016,Austin TX,1,bachelors,corp,1
4,senior full stack engineer (platform),2021,Seattle,1,bachelors,corp,9
...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,San Francisco,0,bachelors,corp,0
1596,mobile app developer (entry level) (payments),2025,Seattle,0,bachelors,corp,0
1597,principal office administrator (operations),2021,St. Louis,0,bachelors,small_business,13
1598,product manager (growth),2024,Seattle,0,bachelors,small_business,5
1599,mobile app developer intern,2022,Austin TX,0,masters,big_tech,0

In [ ]:
y

0       218205
1       208804
2       283959
3       133057
4       270402
         ...
1595    129758
1596    168929
1597     76086
1598    205385
1599    229205
Name: salary_usd, Length: 1600, dtype: int64

In [ ]:
X= X.copy()

In [ ]:
X["degree_required"].value_counts()

degree_required
bachelors    980
masters      301
none         263
phd           56
Name: count, dtype: int64

In [ ]:
#ordinal encoding

In [ ]:
map_dict = {"none": 0,"bachelors":1,"masters":2,"phd":3}
X["degree_required"]=X["degree_required"].map(map_dict)

In [ ]:
X

,job_text,year,metro,remote,degree_required,company_type,years_experience
0,staff product manager (B2B),2020,Austin TX,0,1,startup,10
1,senior cloud infrastructure engineer (cloud),2024,Boston,0,1,corp,6
2,cloud infrastructure engineer (cloud),2024,San Francisco,0,2,big_tech,3
3,frontend engineer (new grad) (distributed syst...,2016,Austin TX,1,1,corp,1
4,senior full stack engineer (platform),2021,Seattle,1,1,corp,9
...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,San Francisco,0,1,corp,0
1596,mobile app developer (entry level) (payments),2025,Seattle,0,1,corp,0
1597,principal office administrator (operations),2021,St. Louis,0,1,small_business,13
1598,product manager (growth),2024,Seattle,0,1,small_business,5
1599,mobile app developer intern,2022,Austin TX,0,2,big_tech,0

In [ ]:
X["company_type"].value_counts()

company_type
corp              524
big_tech          409
startup           397
small_business    270
Name: count, dtype: int64

In [ ]:
#OHE

In [ ]:

X = pd.get_dummies(X,columns= ["company_type"],dtype= np.int32)

In [ ]:

X

,job_text,year,metro,remote,degree_required,years_experience,company_type_big_tech,company_type_corp,company_type_small_business,company_type_startup
0,staff product manager (B2B),2020,Austin TX,0,1,10,0,0,0,1
1,senior cloud infrastructure engineer (cloud),2024,Boston,0,1,6,0,1,0,0
2,cloud infrastructure engineer (cloud),2024,San Francisco,0,2,3,1,0,0,0
3,frontend engineer (new grad) (distributed syst...,2016,Austin TX,1,1,1,0,1,0,0
4,senior full stack engineer (platform),2021,Seattle,1,1,9,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,San Francisco,0,1,0,0,1,0,0
1596,mobile app developer (entry level) (payments),2025,Seattle,0,1,0,0,1,0,0
1597,principal office administrator (operations),2021,St. Louis,0,1,13,0,0,1,0
1598,product manager (growth),2024,Seattle,0,1,5,0,0,1,0
1599,mobile app developer intern,2022,Austin TX,0,2,0,1,0,0,0

In [ ]:
X

,job_text,year,metro,remote,degree_required,years_experience,company_type_big_tech,company_type_corp,company_type_small_business,company_type_startup
0,staff product manager (B2B),2020,Austin TX,0,1,10,0,0,0,1
1,senior cloud infrastructure engineer (cloud),2024,Boston,0,1,6,0,1,0,0
2,cloud infrastructure engineer (cloud),2024,San Francisco,0,2,3,1,0,0,0
3,frontend engineer (new grad) (distributed syst...,2016,Austin TX,1,1,1,0,1,0,0
4,senior full stack engineer (platform),2021,Seattle,1,1,9,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,San Francisco,0,1,0,0,1,0,0
1596,mobile app developer (entry level) (payments),2025,Seattle,0,1,0,0,1,0,0
1597,principal office administrator (operations),2021,St. Louis,0,1,13,0,0,1,0
1598,product manager (growth),2024,Seattle,0,1,5,0,0,1,0
1599,mobile app developer intern,2022,Austin TX,0,2,0,1,0,0,0

In [ ]:
X["metro"].value_counts()

metro
San Francisco     317
New York City     278
Seattle           186
Austin TX         121
Boston            118
Denver            107
Raleigh NC         88
St. Louis          52
Buffalo            46
Boulder            43
Orlando            39
Philadelphia       36
San Antonio        36
Kansas City MO     31
Chicago            30
Dallas             30
Miami              27
Boise ID            2
Bloomington IN      2
New Orleans LA      1
Providence RI       1
Des Moines IA       1
Hartford CT         1
Richmond VA         1
Birmingham AL       1
Columbus OH         1
Princeton NJ        1
Pittsburgh PA       1
Little Rock AR      1
Omaha NE            1
Name: count, dtype: int64

In [ ]:
X

,job_text,year,metro,remote,degree_required,years_experience,company_type_big_tech,company_type_corp,company_type_small_business,company_type_startup
0,staff product manager (B2B),2020,Austin TX,0,1,10,0,0,0,1
1,senior cloud infrastructure engineer (cloud),2024,Boston,0,1,6,0,1,0,0
2,cloud infrastructure engineer (cloud),2024,San Francisco,0,2,3,1,0,0,0
3,frontend engineer (new grad) (distributed syst...,2016,Austin TX,1,1,1,0,1,0,0
4,senior full stack engineer (platform),2021,Seattle,1,1,9,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,San Francisco,0,1,0,0,1,0,0
1596,mobile app developer (entry level) (payments),2025,Seattle,0,1,0,0,1,0,0
1597,principal office administrator (operations),2021,St. Louis,0,1,13,0,0,1,0
1598,product manager (growth),2024,Seattle,0,1,5,0,0,1,0
1599,mobile app developer intern,2022,Austin TX,0,2,0,1,0,0,0

In [ ]:
#grouping rare metro areas into "Other" so the model can learn better and handle unfamiliar locations.

In [ ]:
frequent_metros = X["metro"].value_counts()
frequent_metros = frequent_metros[frequent_metros >= 100].index

X.loc[~X["metro"].isin(frequent_metros), "metro"] = "Other"

X = pd.get_dummies(X, columns=["metro"], dtype=np.int32)

In [ ]:
X

,job_text,year,remote,degree_required,years_experience,company_type_big_tech,company_type_corp,company_type_small_business,company_type_startup,metro_Austin TX,metro_Boston,metro_Denver,metro_New York City,metro_Other,metro_San Francisco,metro_Seattle
0,staff product manager (B2B),2020,0,1,10,0,0,0,1,1,0,0,0,0,0,0
1,senior cloud infrastructure engineer (cloud),2024,0,1,6,0,1,0,0,0,1,0,0,0,0,0
2,cloud infrastructure engineer (cloud),2024,0,2,3,1,0,0,0,0,0,0,0,0,1,0
3,frontend engineer (new grad) (distributed syst...,2016,1,1,1,0,1,0,0,1,0,0,0,0,0,0
4,senior full stack engineer (platform),2021,1,1,9,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,0,1,0,0,1,0,0,0,0,0,0,0,1,0
1596,mobile app developer (entry level) (payments),2025,0,1,0,0,1,0,0,0,0,0,0,0,0,1
1597,principal office administrator (operations),2021,0,1,13,0,0,1,0,0,0,0,0,1,0,0
1598,product manager (growth),2024,0,1,5,0,0,1,0,0,0,0,0,0,0,1
1599,mobile app developer intern,2022,0,2,0,1,0,0,0,1,0,0,0,0,0,0

In [ ]:
#working on the last column

In [ ]:
vec= CountVectorizer()
vec.fit(X["job_text"])

CountVectorizer()

In [ ]:
vec.get_feature_names_out()

array(['administrative', 'administrator', 'ai', 'analyst', 'analytics',
       'app', 'applied', 'assistant', 'b2b', 'backend', 'bi', 'business',
       'cloud', 'computer', 'coordinator', 'dashboarding', 'data', 'desk',
       'desktop', 'developer', 'distributed', 'engineer', 'entry',
       'executive', 'experimentation', 'finance', 'frontend', 'full',
       'generative', 'grad', 'growth', 'help', 'hr', 'infrastructure',
       'intern', 'it', 'junior', 'lead', 'learning', 'level', 'llms',
       'mac', 'machine', 'manager', 'ml', 'mlops', 'mobile', 'models',
       'network', 'networking', 'new', 'nlp', 'office', 'operations',
       'payments', 'platform', 'principal', 'product', 'program',
       'project', 'recommendation', 'recruiting', 'reliability',
       'research', 'saas', 'scientist', 'security', 'senior', 'site',
       'software', 'specialist', 'sql', 'stack', 'staff', 'support',
       'systems', 'technical', 'technician', 'vision', 'windows'],
      dtype=object)

In [ ]:
X_txt= vec.transform(X["job_text"])

In [ ]:
X_txt

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6612 stored elements and shape (1600, 80)>

In [ ]:
X_txt.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X["job_text"].iloc[0]

'staff product manager (B2B)'

In [ ]:
X

,job_text,year,remote,degree_required,years_experience,company_type_big_tech,company_type_corp,company_type_small_business,company_type_startup,metro_Austin TX,metro_Boston,metro_Denver,metro_New York City,metro_Other,metro_San Francisco,metro_Seattle
0,staff product manager (B2B),2020,0,1,10,0,0,0,1,1,0,0,0,0,0,0
1,senior cloud infrastructure engineer (cloud),2024,0,1,6,0,1,0,0,0,1,0,0,0,0,0
2,cloud infrastructure engineer (cloud),2024,0,2,3,1,0,0,0,0,0,0,0,0,1,0
3,frontend engineer (new grad) (distributed syst...,2016,1,1,1,0,1,0,0,1,0,0,0,0,0,0
4,senior full stack engineer (platform),2021,1,1,9,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,BI analyst (entry level) (experimentation),2021,0,1,0,0,1,0,0,0,0,0,0,0,1,0
1596,mobile app developer (entry level) (payments),2025,0,1,0,0,1,0,0,0,0,0,0,0,0,1
1597,principal office administrator (operations),2021,0,1,13,0,0,1,0,0,0,0,0,1,0,0
1598,product manager (growth),2024,0,1,5,0,0,1,0,0,0,0,0,0,0,1
1599,mobile app developer intern,2022,0,2,0,1,0,0,0,1,0,0,0,0,0,0

In [ ]:
#adding X_txt back into X

In [ ]:
col_names = ["job_text_" + n for n in vec.get_feature_names_out() ]
X_txt_df = pd.DataFrame(X_txt.toarray(), columns = col_names)

In [ ]:
X_txt_df

,job_text_administrative,job_text_administrator,job_text_ai,job_text_analyst,job_text_analytics,job_text_app,job_text_applied,job_text_assistant,job_text_b2b,job_text_backend,...,job_text_specialist,job_text_sql,job_text_stack,job_text_staff,job_text_support,job_text_systems,job_text_technical,job_text_technician,job_text_vision,job_text_windows
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1596,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1597,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1598,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1599,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X= pd.concat([X_txt_df,X],axis =1)

In [ ]:
X

,job_text_administrative,job_text_administrator,job_text_ai,job_text_analyst,job_text_analytics,job_text_app,job_text_applied,job_text_assistant,job_text_b2b,job_text_backend,...,company_type_corp,company_type_small_business,company_type_startup,metro_Austin TX,metro_Boston,metro_Denver,metro_New York City,metro_Other,metro_San Francisco,metro_Seattle
0,0,0,0,0,0,0,0,0,1,0,...,0,0,1,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1596,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
1597,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1598,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1599,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
X.columns

Index(['job_text_administrative', 'job_text_administrator', 'job_text_ai',
       'job_text_analyst', 'job_text_analytics', 'job_text_app',
       'job_text_applied', 'job_text_assistant', 'job_text_b2b',
       'job_text_backend', 'job_text_bi', 'job_text_business',
       'job_text_cloud', 'job_text_computer', 'job_text_coordinator',
       'job_text_dashboarding', 'job_text_data', 'job_text_desk',
       'job_text_desktop', 'job_text_developer', 'job_text_distributed',
       'job_text_engineer', 'job_text_entry', 'job_text_executive',
       'job_text_experimentation', 'job_text_finance', 'job_text_frontend',
       'job_text_full', 'job_text_generative', 'job_text_grad',
       'job_text_growth', 'job_text_help', 'job_text_hr',
       'job_text_infrastructure', 'job_text_intern', 'job_text_it',
       'job_text_junior', 'job_text_lead', 'job_text_learning',
       'job_text_level', 'job_text_llms', 'job_text_mac', 'job_text_machine',
       'job_text_manager', 'job_text_ml', 'job_text_mlops', 'job_text_mobile',
       'job_text_models', 'job_text_network', 'job_text_networking',
       'job_text_new', 'job_text_nlp', 'job_text_office',
       'job_text_operations', 'job_text_payments', 'job_text_platform',
       'job_text_principal', 'job_text_product', 'job_text_program',
       'job_text_project', 'job_text_recommendation', 'job_text_recruiting',
       'job_text_reliability', 'job_text_research', 'job_text_saas',
       'job_text_scientist', 'job_text_security', 'job_text_senior',
       'job_text_site', 'job_text_software', 'job_text_specialist',
       'job_text_sql', 'job_text_stack', 'job_text_staff', 'job_text_support',
       'job_text_systems', 'job_text_technical', 'job_text_technician',
       'job_text_vision', 'job_text_windows', 'job_text', 'year', 'remote',
       'degree_required', 'years_experience', 'company_type_big_tech',
       'company_type_corp', 'company_type_small_business',
       'company_type_startup', 'metro_Austin TX', 'metro_Boston',
       'metro_Denver', 'metro_New York City', 'metro_Other',
       'metro_San Francisco', 'metro_Seattle'],
      dtype='object')

In [ ]:
"job_text" in X

True

In [ ]:
X= X.drop("job_text",axis = 1)

In [ ]:
X

,job_text_administrative,job_text_administrator,job_text_ai,job_text_analyst,job_text_analytics,job_text_app,job_text_applied,job_text_assistant,job_text_b2b,job_text_backend,...,company_type_corp,company_type_small_business,company_type_startup,metro_Austin TX,metro_Boston,metro_Denver,metro_New York City,metro_Other,metro_San Francisco,metro_Seattle
0,0,0,0,0,0,0,0,0,1,0,...,0,0,1,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1596,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
1597,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1598,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1599,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 95 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   job_text_administrative      1600 non-null   int64
 1   job_text_administrator       1600 non-null   int64
 2   job_text_ai                  1600 non-null   int64
 3   job_text_analyst             1600 non-null   int64
 4   job_text_analytics           1600 non-null   int64
 5   job_text_app                 1600 non-null   int64
 6   job_text_applied             1600 non-null   int64
 7   job_text_assistant           1600 non-null   int64
 8   job_text_b2b                 1600 non-null   int64
 9   job_text_backend             1600 non-null   int64
 10  job_text_bi                  1600 non-null   int64
 11  job_text_business            1600 non-null   int64
 12  job_text_cloud               1600 non-null   int64
 13  job_text_computer            1600 non-null   int64
 14  job_text_coordinator         1600 non-null   int64
 15  job_text_dashboarding        1600 non-null   int64
 16  job_text_data                1600 non-null   int64
 17  job_text_desk                1600 non-null   int64
 18  job_text_desktop             1600 non-null   int64
 19  job_text_developer           1600 non-null   int64
 20  job_text_distributed         1600 non-null   int64
 21  job_text_engineer            1600 non-null   int64
 22  job_text_entry               1600 non-null   int64
 23  job_text_executive           1600 non-null   int64
 24  job_text_experimentation     1600 non-null   int64
 25  job_text_finance             1600 non-null   int64
 26  job_text_frontend            1600 non-null   int64
 27  job_text_full                1600 non-null   int64
 28  job_text_generative          1600 non-null   int64
 29  job_text_grad                1600 non-null   int64
 30  job_text_growth              1600 non-null   int64
 31  job_text_help                1600 non-null   int64
 32  job_text_hr                  1600 non-null   int64
 33  job_text_infrastructure      1600 non-null   int64
 34  job_text_intern              1600 non-null   int64
 35  job_text_it                  1600 non-null   int64
 36  job_text_junior              1600 non-null   int64
 37  job_text_lead                1600 non-null   int64
 38  job_text_learning            1600 non-null   int64
 39  job_text_level               1600 non-null   int64
 40  job_text_llms                1600 non-null   int64
 41  job_text_mac                 1600 non-null   int64
 42  job_text_machine             1600 non-null   int64
 43  job_text_manager             1600 non-null   int64
 44  job_text_ml                  1600 non-null   int64
 45  job_text_mlops               1600 non-null   int64
 46  job_text_mobile              1600 non-null   int64
 47  job_text_models              1600 non-null   int64
 48  job_text_network             1600 non-null   int64
 49  job_text_networking          1600 non-null   int64
 50  job_text_new                 1600 non-null   int64
 51  job_text_nlp                 1600 non-null   int64
 52  job_text_office              1600 non-null   int64
 53  job_text_operations          1600 non-null   int64
 54  job_text_payments            1600 non-null   int64
 55  job_text_platform            1600 non-null   int64
 56  job_text_principal           1600 non-null   int64
 57  job_text_product             1600 non-null   int64
 58  job_text_program             1600 non-null   int64
 59  job_text_project             1600 non-null   int64
 60  job_text_recommendation      1600 non-null   int64
 61  job_text_recruiting          1600 non-null   int64
 62  job_text_reliability         1600 non-null   int64
 63  job_text_research            1600 non-null   int64
 64  job_text_saas                1600 non-null   int64
 65  job_text_scientist           1600 non-null   int64
 66  job_text_security            1600 non-null   int64
 67  job_text_senior              1600 non-null   int64
 68  job_text_site                1600 non-null   int64
 69  job_text_software            1600 non-null   int64
 70  job_text_specialist          1600 non-null   int64
 71  job_text_sql                 1600 non-null   int64
 72  job_text_stack               1600 non-null   int64
 73  job_text_staff               1600 non-null   int64
 74  job_text_support             1600 non-null   int64
 75  job_text_systems             1600 non-null   int64
 76  job_text_technical           1600 non-null   int64
 77  job_text_technician          1600 non-null   int64
 78  job_text_vision              1600 non-null   int64
 79  job_text_windows             1600 non-null   int64
 80  year                         1600 non-null   int64
 81  remote                       1600 non-null   int64
 82  degree_required              1600 non-null   int64
 83  years_experience             1600 non-null   int64
 84  company_type_big_tech        1600 non-null   int32
 85  company_type_corp            1600 non-null   int32
 86  company_type_small_business  1600 non-null   int32
 87  company_type_startup         1600 non-null   int32
 88  metro_Austin TX              1600 non-null   int32
 89  metro_Boston                 1600 non-null   int32
 90  metro_Denver                 1600 non-null   int32
 91  metro_New York City          1600 non-null   int32
 92  metro_Other                  1600 non-null   int32
 93  metro_San Francisco          1600 non-null   int32
 94  metro_Seattle                1600 non-null   int32
dtypes: int32(11), int64(84)
memory usage: 1.1 MB

In [ ]:
X["year"]

0       2020
1       2024
2       2024
3       2016
4       2021
        ...
1595    2021
1596    2025
1597    2021
1598    2024
1599    2022
Name: year, Length: 1600, dtype: int64

In [ ]:
X.sort_values("year")

,job_text_administrative,job_text_administrator,job_text_ai,job_text_analyst,job_text_analytics,job_text_app,job_text_applied,job_text_assistant,job_text_b2b,job_text_backend,...,company_type_corp,company_type_small_business,company_type_startup,metro_Austin TX,metro_Boston,metro_Denver,metro_New York City,metro_Other,metro_San Francisco,metro_Seattle
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1228,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
495,0,1,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
453,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
507,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
728,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,1,0,0
1441,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
609,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
631,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0

In [ ]:
X["year"]

0       2020
1       2024
2       2024
3       2016
4       2021
        ...
1595    2021
1596    2025
1597    2021
1598    2024
1599    2022
Name: year, Length: 1600, dtype: int64

In [ ]:
y= y.loc[X.index]

In [ ]:
y

0       218205
1       208804
2       283959
3       133057
4       270402
         ...
1595    129758
1596    168929
1597     76086
1598    205385
1599    229205
Name: salary_usd, Length: 1600, dtype: int64

In [ ]:
#assumming this is the test set

In [ ]:
df_test = pd.DataFrame(
    {"job_id": ["A1B2C3", "D4E5F6"],
    "job_text": ["senior data analyst", "quantum network engineer"],
    "year": [2026, 2026],
    "metro": ["New York City", "Albuquerque NM"],
    "remote": [1, 0],
    "degree_required": ["masters", "bachelors"],
    "company_type": ["corp", "startup"],
    "years_experience": [5, 2],
    "salary_usd": [120000, 90000]}
    )

In [ ]:
df_test

,job_id,job_text,year,metro,remote,degree_required,company_type,years_experience,salary_usd
0,A1B2C3,senior data analyst,2026,New York City,1,masters,corp,5,120000
1,D4E5F6,quantum network engineer,2026,Albuquerque NM,0,bachelors,startup,2,90000

In [ ]:
y_test= df_test["salary_usd"]
features = ["job_text",	"year",	"metro",	"remote",	"degree_required",	"company_type",	"years_experience"]

X_test= df_test[features]

In [ ]:
y_test

0    120000
1     90000
Name: salary_usd, dtype: int64

In [ ]:
X_test= X_test.copy()

In [ ]:
#OHE for company_type

In [ ]:
X_test["company_type"].value_counts()

company_type
corp       1
startup    1
Name: count, dtype: int64

In [ ]:
X_test = pd.get_dummies(X_test,columns =["company_type","metro"],dtype = np.int32)

In [ ]:
X_test

,job_text,year,remote,degree_required,years_experience,company_type_corp,company_type_startup,metro_Albuquerque NM,metro_New York City
0,senior data analyst,2026,1,masters,5,1,0,0,1
1,quantum network engineer,2026,0,bachelors,2,0,1,1,0

In [ ]:

#Ordinal Encoding for degree
map_dict = {"bachelors":1, "masters":2}
X_test["degree_required"] = X_test["degree_required"].map(map_dict)

In [ ]:
X_test

,job_text,year,remote,degree_required,years_experience,company_type_corp,company_type_startup,metro_Albuquerque NM,metro_New York City
0,senior data analyst,2026,1,2,5,1,0,0,1
1,quantum network engineer,2026,0,1,2,0,1,1,0

In [ ]:
##last one

In [ ]:
#vec already fitted with the training set will be used to tranform the test set
X_test_txt= vec.transform(X_test["job_text"])

In [ ]:
X_test_txt

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (2, 80)>

In [ ]:
X_test_txt.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
X_test

,job_text,year,remote,degree_required,years_experience,company_type_corp,company_type_startup,metro_Albuquerque NM,metro_New York City
0,senior data analyst,2026,1,2,5,1,0,0,1
1,quantum network engineer,2026,0,1,2,0,1,1,0

In [ ]:
X_test_txt = pd.DataFrame(X_test_txt.toarray(), index=X_test.index)
X_test = pd.concat([X_test.drop(columns=["job_text"]), X_test_txt], axis=1)

In [ ]:
X_test

,year,remote,degree_required,years_experience,company_type_corp,company_type_startup,metro_Albuquerque NM,metro_New York City,0,1,...,70,71,72,73,74,75,76,77,78,79
0,2026,1,2,5,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2026,0,1,2,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0